// source: axon.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.axon.Graph');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.axon.Comment');
goog.require('proto.axon.DataEdge');
goog.require('proto.axon.ExecEdge');
goog.require('proto.axon.Node');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.axon.Graph = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.axon.Graph.repeatedFields_, null);
};
goog.inherits(proto.axon.Graph, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.axon.Graph.displayName = 'proto.axon.Graph';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.axon.Graph.repeatedFields_ = [3,4,5,6,7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.axon.Graph.prototype.toObject = function(opt_includeInstance) {
  return proto.axon.Graph.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.axon.Graph} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.axon.Graph.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    importsList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    nodesList: jspb.Message.toObjectList(msg.getNodesList(),
    proto.axon.Node.toObject, includeInstance),
    dataEdgesList: jspb.Message.toObjectList(msg.getDataEdgesList(),
    proto.axon.DataEdge.toObject, includeInstance),
    execEdgesList: jspb.Message.toObjectList(msg.getExecEdgesList(),
    proto.axon.ExecEdge.toObject, includeInstance),
    commentsList: jspb.Message.toObjectList(msg.getCommentsList(),
    proto.axon.Comment.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.axon.Graph}
 */
proto.axon.Graph.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.axon.Graph;
  return proto.axon.Graph.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.axon.Graph} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.axon.Graph}
 */
proto.axon.Graph.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addImports(value);
      break;
    case 4:
      var value = new proto.axon.Node;
      reader.readMessage(value,proto.axon.Node.deserializeBinaryFromReader);
      msg.addNodes(value);
      break;
    case 5:
      var value = new proto.axon.DataEdge;
      reader.readMessage(value,proto.axon.DataEdge.deserializeBinaryFromReader);
      msg.addDataEdges(value);
      break;
    case 6:
      var value = new proto.axon.ExecEdge;
      reader.readMessage(value,proto.axon.ExecEdge.deserializeBinaryFromReader);
      msg.addExecEdges(value);
      break;
    case 7:
      var value = new proto.axon.Comment;
      reader.readMessage(value,proto.axon.Comment.deserializeBinaryFromReader);
      msg.addComments(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.axon.Graph.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.axon.Graph.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.axon.Graph} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.axon.Graph.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getImportsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getNodesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.axon.Node.serializeBinaryToWriter
    );
  }
  f = message.getDataEdgesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.axon.DataEdge.serializeBinaryToWriter
    );
  }
  f = message.getExecEdgesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.axon.ExecEdge.serializeBinaryToWriter
    );
  }
  f = message.getCommentsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      proto.axon.Comment.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.axon.Graph.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.axon.Graph} returns this
 */
proto.axon.Graph.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.axon.Graph.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.axon.Graph} returns this
 */
proto.axon.Graph.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string imports = 3;
 * @return {!Array<string>}
 */
proto.axon.Graph.prototype.getImportsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.axon.Graph} returns this
 */
proto.axon.Graph.prototype.setImportsList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.axon.Graph} returns this
 */
proto.axon.Graph.prototype.addImports = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.axon.Graph} returns this
 */
proto.axon.Graph.prototype.clearImportsList = function() {
  return this.setImportsList([]);
};


/**
 * repeated Node nodes = 4;
 * @return {!Array<!proto.axon.Node>}
 */
proto.axon.Graph.prototype.getNodesList = function() {
  return /** @type{!Array<!proto.axon.Node>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.axon.Node, 4));
};


/**
 * @param {!Array<!proto.axon.Node>} value
 * @return {!proto.axon.Graph} returns this
*/
proto.axon.Graph.prototype.setNodesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.axon.Node=} opt_value
 * @param {number=} opt_index
 * @return {!proto.axon.Node}
 */
proto.axon.Graph.prototype.addNodes = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.axon.Node, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.axon.Graph} returns this
 */
proto.axon.Graph.prototype.clearNodesList = function() {
  return this.setNodesList([]);
};


/**
 * repeated DataEdge data_edges = 5;
 * @return {!Array<!proto.axon.DataEdge>}
 */
proto.axon.Graph.prototype.getDataEdgesList = function() {
  return /** @type{!Array<!proto.axon.DataEdge>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.axon.DataEdge, 5));
};


/**
 * @param {!Array<!proto.axon.DataEdge>} value
 * @return {!proto.axon.Graph} returns this
*/
proto.axon.Graph.prototype.setDataEdgesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.axon.DataEdge=} opt_value
 * @param {number=} opt_index
 * @return {!proto.axon.DataEdge}
 */
proto.axon.Graph.prototype.addDataEdges = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.axon.DataEdge, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.axon.Graph} returns this
 */
proto.axon.Graph.prototype.clearDataEdgesList = function() {
  return this.setDataEdgesList([]);
};


/**
 * repeated ExecEdge exec_edges = 6;
 * @return {!Array<!proto.axon.ExecEdge>}
 */
proto.axon.Graph.prototype.getExecEdgesList = function() {
  return /** @type{!Array<!proto.axon.ExecEdge>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.axon.ExecEdge, 6));
};


/**
 * @param {!Array<!proto.axon.ExecEdge>} value
 * @return {!proto.axon.Graph} returns this
*/
proto.axon.Graph.prototype.setExecEdgesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.axon.ExecEdge=} opt_value
 * @param {number=} opt_index
 * @return {!proto.axon.ExecEdge}
 */
proto.axon.Graph.prototype.addExecEdges = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.axon.ExecEdge, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.axon.Graph} returns this
 */
proto.axon.Graph.prototype.clearExecEdgesList = function() {
  return this.setExecEdgesList([]);
};


/**
 * repeated Comment comments = 7;
 * @return {!Array<!proto.axon.Comment>}
 */
proto.axon.Graph.prototype.getCommentsList = function() {
  return /** @type{!Array<!proto.axon.Comment>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.axon.Comment, 7));
};


/**
 * @param {!Array<!proto.axon.Comment>} value
 * @return {!proto.axon.Graph} returns this
*/
proto.axon.Graph.prototype.setCommentsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.axon.Comment=} opt_value
 * @param {number=} opt_index
 * @return {!proto.axon.Comment}
 */
proto.axon.Graph.prototype.addComments = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.axon.Comment, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.axon.Graph} returns this
 */
proto.axon.Graph.prototype.clearCommentsList = function() {
  return this.setCommentsList([]);
};


