// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadGraphFromFile(arg1) {
  return window['go']['main']['App']['LoadGraphFromFile'](arg1);
}

export function SaveGraphToFile(arg1, arg2) {
  return window['go']['main']['App']['SaveGraphToFile'](arg1, arg2);
}

export function TranspileGraph(arg1) {
  return window['go']['main']['App']['TranspileGraph'](arg1);
}
