// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {axon} from '../models';

export function LoadGraphFromFile(arg1:string):Promise<axon.Graph>;

export function SaveGraphToFile(arg1:string,arg2:axon.Graph):Promise<void>;

export function TranspileGraph(arg1:axon.Graph):Promise<string>;
