// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {lsp} from '../models';

export function BuildGraph(arg1:string):Promise<string>;

export function GenerateGoCode(arg1:string):Promise<string>;

export function GetCompletions(arg1:string):Promise<Array<lsp.CompletionItem>>;

export function GetHoverInfo(arg1:string,arg2:string):Promise<string>;

export function OpenFile():Promise<string>;

export function RunGraph(arg1:string):Promise<string>;

export function SaveFile(arg1:string):Promise<void>;

export function ValidateGraph(arg1:string):Promise<Array<lsp.Diagnostic>>;
