// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildGraph(arg1) {
  return window['go']['main']['App']['BuildGraph'](arg1);
}

export function GenerateGoCode(arg1) {
  return window['go']['main']['App']['GenerateGoCode'](arg1);
}

export function GetCompletions(arg1) {
  return window['go']['main']['App']['GetCompletions'](arg1);
}

export function GetHoverInfo(arg1, arg2) {
  return window['go']['main']['App']['GetHoverInfo'](arg1, arg2);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function RunGraph(arg1) {
  return window['go']['main']['App']['RunGraph'](arg1);
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function ValidateGraph(arg1) {
  return window['go']['main']['App']['ValidateGraph'](arg1);
}
